# Generated by Django 5.0.1 on 2024-01-09 06:41

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_turn",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelCard",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("object", models.CharField(default="model", max_length=255)),
                ("created", models.IntegerField(default=1704782477)),
                ("owned_by", models.CharField(default="openchat", max_length=255)),
                ("root", models.CharField(blank=True, max_length=255, null=True)),
                ("parent", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object", models.CharField(default="list", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ModelPermission",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="modelperm",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object",
                    models.CharField(default="model_permission", max_length=255),
                ),
                ("created", models.IntegerField(default=1704782477)),
                ("allow_create_engine", models.BooleanField(default=False)),
                ("allow_sampling", models.BooleanField(default=True)),
                ("allow_logprobs", models.BooleanField(default=False)),
                ("allow_search_indices", models.BooleanField(default=False)),
                ("allow_view", models.BooleanField(default=True)),
                ("allow_fine_tuning", models.BooleanField(default=False)),
                ("organization", models.CharField(default="*", max_length=255)),
                ("group", models.CharField(blank=True, max_length=255, null=True)),
                ("is_blocking", models.BooleanField(default=False)),
            ],
        ),
    ]
