# Generated by Django 5.0.1 on 2024-01-09 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatresponse",
            name="chat_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="chat.chat",
            ),
        ),
        migrations.AddField(
            model_name="modellist",
            name="data",
            field=models.ManyToManyField(blank=True, to="chat.modelcard"),
        ),
        migrations.AddField(
            model_name="modelcard",
            name="permission",
            field=models.ManyToManyField(blank=True, to="chat.modelpermission"),
        ),
    ]
