# Generated by Django 5.0.1 on 2024-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcard",
            name="created",
            field=models.IntegerField(default=1704810598),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="created",
            field=models.IntegerField(default=1704810598),
        ),
    ]
