# Generated by Django 5.0.1 on 2024-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_modelcard_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcard",
            name="created",
            field=models.IntegerField(default=1704812692),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="created",
            field=models.IntegerField(default=1704812692),
        ),
    ]
